name: The Grid Test Location - Stealth Model
favicon: null
layout_spectrum: 1
typography_spectrum: 0.58961
title: The Definitive Grid State of The Union
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74654992-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#333333'
    - '#d53e1b'
    - '#969696'
  brandStrength: 1
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
